#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'Styling, testing and building your project before committing...'

pnpm lint-staged
pnpm lint

echo 'Trying to build...'

pnpm build ||
    (
        echo 'Next build failed: View the errors above to see why.'
        false
    )

echo 'All checks succeeded'
